name: publish-6_0

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-6_0:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Get repository name
        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash
      -
        name: Read .NET version - revision
        uses: bfren/read-file@v2
        with:
          file: ./6.0/overlay/tmp/DOTNET_REVISION
        id: dotnet_revision
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MAJOR
        id: version_major
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION_MINOR
        id: version_minor
      -
        name: Read image version
        uses: bfren/read-file@v2
        with:
          file: ./VERSION
        id: version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./6.0/Dockerfile
          build-args: |
            BF_IMAGE=${{ env.REPOSITORY_NAME }}
            BF_VERSION=${{ steps.version.outputs.contents }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            bfren/aspnet:net6
            bfren/aspnet:net6-${{ steps.version_major.outputs.contents }}
            bfren/aspnet:net6-${{ steps.version_minor.outputs.contents }}
            bfren/aspnet:net6-${{ steps.version.outputs.contents }}
            bfren/aspnet:net6.0
            bfren/aspnet:net6.0-${{ steps.version_major.outputs.contents }}
            bfren/aspnet:net6.0-${{ steps.version_minor.outputs.contents }}
            bfren/aspnet:net6.0-${{ steps.version.outputs.contents }}
            bfren/aspnet:net${{ steps.dotnet_revision.outputs.contents }}
            ghcr.io/bfren/aspnet:net6
            ghcr.io/bfren/aspnet:net6-${{ steps.version_major.outputs.contents }}
            ghcr.io/bfren/aspnet:net6-${{ steps.version_minor.outputs.contents }}
            ghcr.io/bfren/aspnet:net6-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/aspnet:net6.0
            ghcr.io/bfren/aspnet:net6.0-${{ steps.version_major.outputs.contents }}
            ghcr.io/bfren/aspnet:net6.0-${{ steps.version_minor.outputs.contents }}
            ghcr.io/bfren/aspnet:net6.0-${{ steps.version.outputs.contents }}
            ghcr.io/bfren/aspnet:net${{ steps.dotnet_revision.outputs.contents }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
